### PR TITLE
test: Break Up Tests

### PR DESCRIPTION
**Pull request by ciband**
Refactored unit tests on PlatformIO into smaller groups.  This allows for smaller unit test program images for easier testing on boards that have a smaller flash size.

This also paves the way for a hardware testing appliance to be created to aid in testing IoT.

This patch also proved out unit tests support for ESP8266 va googletest, but the ESP8226 tests are disabled due to pending PR merge in googltest to support the platform.

Tracked in #138 

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Refactor
- [ ] Performance
- [x] Tests
- [x] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by sleepdefic1t** [comment]
@faustbrian 
Can you retrigger Appveyor here as well when you get a moment, please and thank you.

**Comment by faustbrian** [comment]
@ciband could you merge develop? GitHub for some reason isn't displaying the merge button.

**Comment by ciband** [comment]
@faustbrian 
I do not have an option to rebase or merge develop into this PR from GitHub.  I can try manually.

**Comment by ciband** [comment]
Initial try to push after merging develop got me this:

Error encountered while pushing to the remote repository: rejected refactor/break_up_tests -> refactor/break_up_tests (refusing to allow an integration to create or update .github/workflows/test.yml)

I can look at it later but any ideas?  Github workflow / permissions thing?

**Comment by faustbrian** [comment]
@ciband known issue with the github workflows, will make some adjustments to the configuration tomorrow.

**Pull request merged**
