### PR TITLE
fix: remove adapter header

### PR DESCRIPTION
**Pull request by sleepdefic1t**
## Proposed changes

The Arduino adapter header `src/arkCrypto.h` does not solve Arduino IDE integration and is never used in any builds.

This PR removes the unnecessary Arduino Adapter header.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [ ] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by ciband** [comment]
@sleepdefic1t 

CI isn't pulling the latest BIP39 from the library manager (1.0.1 vs 1.1).  Looking into it.

**Comment by ciband** [comment]
Further review.  PIO isn't ignoring the ./src/lib directory like it should and is compiling in the desktop submodule for BIP39.  Not sure why it isn't respecting the -<src/lib> setting.

**Comment by ciband** [comment]
#52 should fix this now.

**Comment by sleepdefic1t** [comment]
#52 should resolve failing linux build.

**Pull request merged**
