### PR TITLE
chore: Update ArduinoJson Package

### PR DESCRIPTION
**Pull request by sleepdefic1t**
## Proposed changes

The current Cpp-Crypto library supports ArduinoJson v.5 semantics.

This PR updates to and explicitly forces use of ArduinoJson v.6.10.0.

Specifically, this PR changes the following:
- updates version in ./circleci/script_arduino.sh.
- updates version in docs/INSTALL_PLATFORMIO.md.
- updates version in /platformio.ini.
- updates version in test/platformio.ini.
- updates ArduinoJson submodule
- updates transaction.cpp ArduinoJson semantics.
- updates test/transaction.cpp ArduinoJson semantics.
- updates message.cpp ArduinoJson semantics.
- updates test/message.cpp ArduinoJson semantics.

## Types of changes

- [x] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [x] Build (changes that affect the build system)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

## Further comments

This PR also resolves build failure in #74 as noted in #75.

It is **[WIP]** until I can confirm this will pass all CI test.

### CODE REVIEW

**Comment by sleepdefic1t** [comment]
@ciband 
This error look familiar at all?

I didn't touch anything with BIP39.

PIO 32/8266 works just fine on macOS;
Linux PIO ESP8266 apparently not so much.

```
In file included from /home/circleci/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/include/string.h:163:0,
from /home/circleci/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/Arduino.h:33,
from .piolibdeps/bip39_ID5886/src/util.h:13,
from .piolibdeps/bip39_ID5886/src/dictionary/english_str.h:4,
from .piolibdeps/bip39_ID5886/src/dictionary/english.h:4,
from .piolibdeps/bip39_ID5886/src/bip39.cpp:2:
.piolibdeps/bip39_ID5886/src/bip39.cpp: In function 'int BIP39::{anonymous}::get_word_index(const char* const*, const string&)':
.piolibdeps/bip39_ID5886/src/bip39.cpp:52:28: error: 'const void*' is not a pointer-to-object type
strcpy_P(w, (char*)pgm_read_ptr_far(&(lexicon[i]))); // NOLINT
^
/home/circleci/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/include/sys/string.h:32:57: note: in definition of macro 'strcpy_P'
#define strcpy_P(dest, src)          strncpy_P((dest), (src), SIZE_IRRELEVANT)
^
.piolibdeps/bip39_ID5886/src/bip39.cpp: In function 'BIP39::word_list BIP39::create_mnemonic(std::vector<unsigned char>&, BIP39::language)':
.piolibdeps/bip39_ID5886/src/bip39.cpp:106:31: error: 'const void*' is not a pointer-to-object type
strcpy_P(word, (char*)pgm_read_ptr_far(&(lexicon[position]))); // NOLINT
^
/home/circleci/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/include/sys/string.h:32:57: note: in definition of macro 'strcpy_P'
#define strcpy_P(dest, src)          strncpy_P((dest), (src), SIZE_IRRELEVANT)
^
*** [.pioenvs/esp8266/src/test/.piolibdeps/bip39_ID5886/src/bip39.cpp.o] Error 1
```

**Comment by ciband** [comment]
I think some of the interfaces in ESP8266 Arduino libs for PROGMEM strings changed as some point. 

I don’t remember all of the particulars.

**Comment by sleepdefic1t** [comment]
@ciband 
Yeah, I'm guessing 8266 Core changed at some point recently.

Tried this fix in bip39 on a Linux instance, seems to resolve issue.

```cpp
#if defined(ESP8266) |              \
    defined(ARDUINO_SAMD_MKRZERO) | \
    defined(ARDUINO_SAMD_ZERO) |    \
    defined(ARDUINO_SAM_DUE) |      \
    defined(ARDUINO_ARCH_ARC32) |   \
    defined(__TC27XX__) |           \
    (defined(TEENSYDUINO) && (TEENSYDUINO < 139))
#undef pgm_read_ptr
#define pgm_read_ptr(addr) (*(const void **)(addr))
#endif
```
> src: https://github.com/SlashDevin/NeoGPS/issues/112

I'll open a PR in ciband/BIP39 so you can check it out.

**Comment by ciband** [comment]
Sounds good.

**Comment by sleepdefic1t** [comment]
Final build error in `ci/circleci: build-linux-default` is related to external BIP39 package.

A PR to resolve that packages build error was submitted @ https://github.com/ciband/bip39/pull/8

This PR should be good to go now 👍

**Pull request merged**
