### PR TITLE
chore: Remove extra copies and add const

### PR DESCRIPTION
**Pull request by ciband**
Removed various pass by value to eliminate extra copies.

Added const and noexcept to various member functions.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [x] Refactor
- [x] Performance
- [ ] Tests
- [ ] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ciband** [comment]
The build errors do not make sense.  They are build system problems and not anything to do with the code in this PR.  I would suggest merging #126  and then rebasing this.  #126 improves build and CI stability.

**Comment by sleepdefic1t** [comment]
Looks like there’s a submodule in CMake examples from #126 that made its way in.

Method updates look good.
Isn’t `Object(const T&)` a copy constructor though, and should we be using rule of 3 or 5 in these instances?

**Comment by ciband** [comment]
@sleepdefic1t  I am not seeing where you are talking about the cmake examples .gitmodule.  That file was not modified as a part of this PR.

For the copy ctor, you are correct.  Was there any area in this PR that I broke?

**Comment by ciband** [comment]
@sleepdefic1t Nevermind on the submodule.  I see it now.  Fix incoming.

**Comment by sleepdefic1t** [comment]
Yup. That’s the one. Lol

Looking at the Tidy output at [circleci/cpp-crypto/1241](https://circleci.com/gh/ArkEcosystem/cpp-crypto/1241), there are few stray `std::move` calls leftover after the updates. One in `message.cpp` and a few in `builder.cpp`.  There might also be a couple lines in `transaction.cpp`.

I think these would be the only things relevant to this PR.
Everything else in the log is pretty much fixed between #121 & #81 

Thank you for the improvements here 👍

**Comment by ciband** [comment]
@sleepdefic1t  I think I got all the clang tidy stuff I introduced.  Please let me know if you need any more changes.  Thanks.

**Pull request merged**
