### PR TITLE
chore:  Add support for Visual Studio 2019

### PR DESCRIPTION
**Pull request by ciband**
Updated CMakeSettings.json to support Visual Studio 2019 compilers and schema.

## What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Refactor
- [ ] Performance
- [ ] Tests
- [x] Build
- [ ] Documentation
- [ ] Code style update
- [ ] Continuous Integration
- [ ] Other, please describe:

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Does this PR release a new version?

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `develop` branch, _not_ the `master` branch
- [x] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

**Comment by ciband** [comment]
As is this moves us forward to 2019 (upgrade). 

If we want to support development on older compilers then we can do that. 

We could also just support the older stuff in CI and keep the configuration small for just develop in 2019.

**Comment by sleepdefic1t** [comment]
@ciband
CI can be 2019.
I’d like to support 2017 & 2019 users.

I just wasn’t sure if having the 2019 config means 2017 users would have to do their own configuration or not.

**Comment by ciband** [comment]
@sleepdefic1t  I think we need to be consistent.  If we want developers to be able to use the 2017 compiler or the 2019 compiler, then I think CI should reflect that (meaning once we actually get Windows CI up and running via Appveyor or CircleCI).

For this PR and its scope, I'm hearing to support both so I will Add the VS2017 configs back in.

**Comment by sleepdefic1t** [comment]
Okay, sounds good.

I know nothing about Windows Dev, I just know a lot of the students we saw at Hackathons didn’t usually have the latest releases. Lots of 2015 configs in repos too, so I don’t want to force people into 2019 if we can just offer it as an option.

I appreciate your guidance on the Windows stuff.
Thanks again, @ciband

**Comment by ciband** [comment]
Appveyor failure due to plan time execution limits.  Debug passed, release was aborted.

This works on VS2019 with the VS2017 changes.  It tries to invoke the VS2017 compiler under VS2019 for the appropriate config.

I still need to test on a pure VS2017 machine to see how it handles the VS2019 configs but I don't foresee any issues.

My laptop HD is small so I had to uninstall VS2017.

**Comment by ciband** [comment]
@sleepdefic1t  VS2017 targets work under VS2017 IDE.  The VS2019 targets to not work, which is expected.  They give reasonable diagnostics as to why they do not work.

I think this PR is ready for review.

**Pull request merged**
