### PR TITLE
feat: Add passphrase generation support

### LINKED ISSUE #23: Add ability to generate passphrases
**Is your feature request related to a problem? Please describe.**
The current crypto implementation does not have a way to generate a passphrase.

**Describe the solution you'd like**
I would like the ability to generate a BIP39 passphrase.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ciband**
## Proposed changes
Added passphrase generation support for English and either 12 words (Ark desktop wallet default) or 24 words (Ledger default)

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Refactoring (improve a current implementation without adding a new feature or fixing a bug)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build (changes that affect the build system)
- [ ] Docs (documentation only changes)
- [X] Test (adding missing tests or fixing existing tests)
- [ ] Other... Please describe:

## Checklist

- [X] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [X] Lint and unit tests pass locally with my changes
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)

## Further comments
Fixes #23 

I chose to use a set of macros to allow for a "cheap" code generator.  This allows for the BIP39 strings to be in data tables.  In the case of Arduino systems, these data tables are stored in program memory to conserve RAM. 

If this approach is approved, I can begin to add the other BIP39 languages.
(see https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md)

Tests pass on ESP32 hardware

### CODE REVIEW

**Comment by ciband** [comment]
Discussion:  Do we want to limit the word could to 12 and 24, or do we want to make it open ended?  If open ended, what would the min/max word counts be?

**Comment by faustbrian** [comment]
BIP39 generation isn't part of the crypto package specs because it isn't specific to Ark and can be done through the official Bitcoin _(thus BIP)_ libraries for each language.

**Comment by ciband** [comment]
I can understand that.  I would push back a little for this reason:

The official bitcoin C++ library is massive, not designed for IoT, and has a dependency on boost which is also not designed for IoT.

By creating our own, we are able to optimized it to work on both the desktop platforms as well as IoT.

If the argument is more about decoupling and not wanting BIP39 implementation in the actual code, then what are your thoughts on me spinning this off into another repo and then using git submodule (or similar)?

**Comment by faustbrian** [comment]
Branching it off and using a sub-module is fine with me.

**Comment by ciband** [comment]
Ok, then I will go that route and re-submit.

**Pull request closed without merging**
