### PR TITLE
(WIP) feat: enable support for esp8266

### PR DESCRIPTION
**Pull request by ciband**
## Summary

Enabled support for ESP8266.  Added supported for ESP8266 in
googletest and turned on ESP8266 unit tests.  Code uses my local fork of google test until ESP8266 support PR is merged into the main codebase.

https://github.com/google/googletest/pull/2432

## Checklist

- [ ] Documentation _(if necessary)_
- [ ] Tests _(if necessary)_
- [ ] Ready to be merged

### CODE REVIEW

**Comment by ciband** [comment]
I still need to test this on hardware but confidence is high.

**Comment by ciband** [comment]
I tested this on ESP8266 hardware last night and found issues.  I'm pretty sure it is software and not my hardware but I"m not 100%.  If someone wanted to sanity check on their ESP8266 hardware, that would be helpful.  I will continue my investigation.

**Comment by sleepdefic1t** [comment]
Just tested today.
Definitely crashing.
Definitely not related to this PR.
Looks like the Arduino and PIO builds for ESP8266 are crashing in Client _and_ Crypto with demo sketches too.

8266 tests have been disabled for a bit, and only ESP32 builds are tested in CI.
So I'm not sure at what point it stopped working or for what reason.

There's also been a few Arduino IDE, PIO, and ESP8266 SDK releases over the past year, so that adds some extra fun to the mix.

Resolving this should be a separate issue.

That said, gtest version here is pre-release, so keeping those extra flags won't work in the current builds.

Unfortunately, there's no reason to merge this if the C++ Crypto lib won't work on ESP8266 to begin with 😞

**Comment by ciband** [comment]
@sleepdefic1t 
ah ok.  I didn't realize that esp8266 support got broken along the way.  Agreed then.  I vote to leave this open and I will work on fixing esp8266 support.

I did not understand the comment about gtest and not working in the current builds.  Would you mind clarifying?  Thanks.

**Comment by sleepdefic1t** [comment]
I was originally thinking we could just comment the 8266 parts and keep the lib_deps flags.

The 8266 parts were already commented there though; and GTest doesn't use an explicit package version, so things could break when new releases are pushed.
Tmk, the C99 call also isn't needed in the current builds.

So I guess "not working" isn't accurate, more should will work until it might not.

I'd prefer closing this unless you think you'll find a fix soon.
I plan to look at fixing 8266 support, but it's a lower priority over Core 2.6 stuff.

**Comment by ciband** [comment]
For gtest, it is just set to the tips of my pre_release branch so it won't move unless I move it.  I can do a release to pin it a little better.  For C99, that should just be for ESP8266.  That slipped through the cracks and should be moved to just ESP8266 targets.

I can understand the 2.6 stuff being a priority.  For me and my time / mental bandwidth, I've hit a wall on the schnorr sign stuff.  ESP8266 support is a little less intense so I can focus on that if you like.

As far as this PR, you can close if you want.  Once esp8266 is working again, I can reopen and rebase.

**Comment by sleepdefic1t** [comment]
#164 resolves ESP32 PIO Test issues.

This PR with #164 fixes still result in ESP8266 crashing (`rst cause:2, boot mode:(3,6)`).

ESP8266 with #164 fixes _**and**_ using AUnit run but eventually crash due to an overflow as expected.

Closing this out and keeping issue #138 open.

**Pull request closed without merging**
