### PR TITLE
build: circleci config init

### PR DESCRIPTION
**Pull request by air1one**
## Proposed changes

CircleCI configuration for building on : 

- linux platformio
- linux clang
- linux gcc7
- macos xcode 9.2 clang
- macos xcode 9.3 gcc

## Types of changes

- [x] Build (changes that affect the build system)

## Checklist

- [x] I have read the [CONTRIBUTING](https://docs.ark.io/guidebook/contribution-guidelines/contributing.html) documentation
- [x] Lint and unit tests pass locally with my changes

### CODE REVIEW

**Comment by air1one** [comment]
Build is failing on linux clang and gcc, can someone familiar with this repo have a look and see what is wrong ?

**Comment by ciband** [comment]
It appears that both Linux builds are still using gcc 4.8.5 when doing the actual build.  This is why the builds are failing as we do not support that old of a compiler.

Why circleci is not respecting the settings in the file, I have no idea.  I have never configured a circleci project before.

**Comment by sleepdefic1t** [comment]
I can confirm that this builds and passes tests on my system:
**(clang-1000.11.45.5) | x86_64-apple-darwin18.0.0**

as @ciband stated, clang version appears to be set in config.
Not sticking in CircleCI per build logs though.

@air1one, do you know if there are any additional steps/solutions to ensure the compiler version matches the config?

**Comment by ciband** [comment]
I got it working in my local repo.  I think the Linux Clang stuff can get cleaned up but I hope it helps.

https://github.com/ciband/cpp-crypto/blob/scratch/circleci/.circleci/config.yml

**Comment by faustbrian** [comment]
@air1one the macOS jobs seem to hang on CircleCI, already restarted once but they hang again.

**Pull request merged**
