### PR TITLE
test: fix ESP8266 Unit Tests

### PR DESCRIPTION
**Pull request by ciband**
## Summary
This PR fixes the broken unit tests for esp8266.  The theme of this PR is breaking up the unit tests to allow the tests to run on the esp8266 hardware without running out of RAM and blowing the stack.

The current status of the PR has all tests passing except to_array and to_json.  These tests simply do not fit into RAM as currently implemented.  I think this should be a different issue and PR.

## Checklist

- [ ] Documentation _(if necessary)_
- [x] Tests _(if necessary)_
- [x] Ready to be merged

Fixes #169 
Depends on #172

### CODE REVIEW

**Comment by ciband** [comment]
CI failures for coverage and Windows look to be CI issues and out of scope for this PR.  

The Windows failure looks like a bug in the script to call the unit test exe.  Should this be written up as an Issue and worked separately?

**Comment by sleepdefic1t** [comment]
Windows Issues addressed in #170 
CodeClimate issues addressed in #171 

This is a good PR, but a fairly sizable one.
I'll give this a proper testing in these next couple days, and we'll see if we can get those other two merged first 👍 

Quick thought, What are your feelings on splitting off the ESP8266/PIO part to a separate PR?
Splitting up tests to fit on smaller devices and enabling ESP8266 support are easily two different things, I'm sure these changes will be useful for more than just the 8266 anyways.

Nice work as always regardless, @ciband 
Thank you.

**Comment by ciband** [comment]
@sleepdefic1t

I agree that this will be helpful on other small RAM platforms.  I certain can split it up but I’m not exactly sure where to draw the line. I’d prefer to keep it as is as I think the changes are all dependent on each other. That being said if you can give me some more details on what you want to split I can work that.

**Comment by sleepdefic1t** [comment]
True, they’re kinda tied together..

But only in that the split up tests enables 8266 to run them successfully.

Splitting them up would, hypothetically, allow tests to pass on other devices too.

So how about this PR just splits the tests with the purpose of enabling smaller platforms to pass unit tests.
Basically, everything except the `IoT/test_main.cpp` and `test/PIO` files.

Those could be in a separate PR that enables 8266 now that the unit tests can support smaller architectures.

**Comment by ciband** [comment]
Split out files as requested.  They are in #172 and they must be merged before this PR.

**Pull request merged**
